### ISSUE TITLE
Add support for nullsafety

### ISSUE THREAD

**Issue by emme1444** [simphotonics/merging_builder#2]
@simphotonics 

Currently blocked by:
- ~~simphotonics/directed_graph#4~~
- ~~dart-lang/source_gen#493~~

**Comment by simphotonics** [comment]
The latest version of `source_gen` is not yet opted into null safety. But it seems the maintainers of `source_gen` are working on migrating their project.

**Comment by emme1444** [comment]
Yes! I was also following their migration closely. 

As of now, however, they have published `1.0.0`. Although it is listed as a min SDK of `1.12 (dev)`. Whether that matters or not I don't know. You tell me. 🤔

**Comment by simphotonics** [comment]
Good to hear that. Just published the migrated version of [`merging_builder`](https://pub.dev/packages/merging_builder) 0.2.0.
